#modloaded tconstruct

// Author : TerraFirmaCraft Reloaded Team & ACGaming
// Mod required : Tinkers' Construct, Construct's Armory, Immersive Engineering
// Scripts required : -

import crafttweaker.liquid.ILiquidDefinition;
import mods.jei.JEI;
import mods.tconstruct.Alloy;
import mods.tconstruct.Casting;
import mods.tconstruct.Drying;
import mods.tconstruct.Fuel;
import mods.tconstruct.Melting;
import mods.terrafirmacraft.Heating;
import mods.terrafirmacraft.ItemRegistry;

// JEI REMOVE AND HIDE
JEI.removeAndHide(<tconstruct:edible:0>);
JEI.removeAndHide(<tconstruct:edible:10>);
JEI.removeAndHide(<tconstruct:edible:11>);
JEI.removeAndHide(<tconstruct:edible:12>);
JEI.removeAndHide(<tconstruct:edible:13>);
JEI.removeAndHide(<tconstruct:edible:14>);
JEI.removeAndHide(<tconstruct:edible:15>);
JEI.removeAndHide(<tconstruct:edible:20>);
JEI.removeAndHide(<tconstruct:edible:21>);
JEI.removeAndHide(<tconstruct:edible:22>);
JEI.removeAndHide(<tconstruct:edible:23>);
JEI.removeAndHide(<tconstruct:edible:30>);
JEI.removeAndHide(<tconstruct:edible:31>);
JEI.removeAndHide(<tconstruct:edible:32>);
JEI.removeAndHide(<tconstruct:edible:33>);
JEI.removeAndHide(<tconstruct:edible:34>);
JEI.removeAndHide(<tconstruct:ingots:5>);
JEI.removeAndHide(<tconstruct:metal:5>);
JEI.removeAndHide(<tconstruct:nuggets:5>);
JEI.removeAndHide(<tconstruct:soil>);

// REMOVE
recipes.remove(<conarm:travel_sack>);
recipes.remove(<tconstruct:ingots:*>);
recipes.remove(<tconstruct:metal:*>);
recipes.remove(<tconstruct:nuggets:*>);
recipes.remove(<tconstruct:seared_furnace_controller>);
recipes.remove(<tconstruct:smeltery_controller>);
recipes.remove(<tconstruct:throwball:1>);
recipes.remove(<tconstruct:tinker_tank_controller>);

// REMOVE CASTING
Casting.removeBasinRecipe(<immersive_energy:storage:1>);
Casting.removeBasinRecipe(<immersive_energy:storage>);
Casting.removeBasinRecipe(<immersiveengineering:storage:1>);
Casting.removeBasinRecipe(<immersiveengineering:storage:2>);
Casting.removeBasinRecipe(<immersiveengineering:storage:3>);
Casting.removeBasinRecipe(<immersiveengineering:storage:4>);
Casting.removeBasinRecipe(<immersiveengineering:storage:5>);
Casting.removeBasinRecipe(<immersiveengineering:storage:6>);
Casting.removeBasinRecipe(<immersiveengineering:storage:7>);
Casting.removeBasinRecipe(<immersiveengineering:storage:8>);
Casting.removeBasinRecipe(<immersiveengineering:storage>);
Casting.removeBasinRecipe(<tconstruct:metal:5>);

Casting.removeTableRecipe(<immersiveengineering:metal:30>);
Casting.removeTableRecipe(<immersiveengineering:metal:31>);
Casting.removeTableRecipe(<immersiveengineering:metal:32>);
Casting.removeTableRecipe(<immersiveengineering:metal:33>);
Casting.removeTableRecipe(<immersiveengineering:metal:34>);
Casting.removeTableRecipe(<immersiveengineering:metal:35>);
Casting.removeTableRecipe(<immersiveengineering:metal:36>);
Casting.removeTableRecipe(<immersiveengineering:metal:37>);
Casting.removeTableRecipe(<immersiveengineering:metal:38>);
Casting.removeTableRecipe(<immersiveengineering:metal:39>);
Casting.removeTableRecipe(<immersiveengineering:metal:40>);
Casting.removeTableRecipe(<tconstruct:ingots:4>);
Casting.removeTableRecipe(<tconstruct:ingots:5>);
Casting.removeTableRecipe(<tconstruct:nuggets:5>);

// REMOVE MELTING
Melting.removeRecipe(<liquid:aluminium>, <contenttweaker:blockaluminium>);
Melting.removeRecipe(<liquid:aluminium_brass>, <contenttweaker:blockaluminium_brass>);
Melting.removeRecipe(<liquid:antimony>, <contenttweaker:blockantimony>);
Melting.removeRecipe(<liquid:ardite>, <contenttweaker:blockardite>);
Melting.removeRecipe(<liquid:beryllium>, <contenttweaker:blockberyllium>);
Melting.removeRecipe(<liquid:beryllium_copper>, <contenttweaker:blockberyllium_copper>);
Melting.removeRecipe(<liquid:bismuth>, <contenttweaker:blockbismuth>);
Melting.removeRecipe(<liquid:bismuth_bronze>, <contenttweaker:blockbismuth_bronze>);
Melting.removeRecipe(<liquid:black_bronze>, <contenttweaker:blockblack_bronze>);
Melting.removeRecipe(<liquid:black_steel>, <contenttweaker:blockblack_steel>);
Melting.removeRecipe(<liquid:blue_steel>, <contenttweaker:blockblue_steel>);
Melting.removeRecipe(<liquid:boron>, <contenttweaker:blockboron>);
Melting.removeRecipe(<liquid:brass>, <contenttweaker:blockbrass>);
Melting.removeRecipe(<liquid:bronze>, <contenttweaker:blockbronze>);
Melting.removeRecipe(<liquid:cobalt>, <contenttweaker:blockcobalt>);
Melting.removeRecipe(<liquid:constantan>, <contenttweaker:blockconstantan>);
Melting.removeRecipe(<liquid:copper>, <contenttweaker:blockcopper>);
Melting.removeRecipe(<liquid:electrum>, <contenttweaker:blockelectrum>);
Melting.removeRecipe(<liquid:ferroboron>, <contenttweaker:blockferroboron>);
Melting.removeRecipe(<liquid:gold>, <contenttweaker:blockgold>);
Melting.removeRecipe(<liquid:hsla_steel>, <contenttweaker:blockhsla_steel>);
Melting.removeRecipe(<liquid:invar>, <contenttweaker:blockinvar>);
Melting.removeRecipe(<liquid:lead>, <contenttweaker:blocklead>);
Melting.removeRecipe(<liquid:lithium>, <contenttweaker:blocklithium>);
Melting.removeRecipe(<liquid:magnesium>, <contenttweaker:blockmagnesium>);
Melting.removeRecipe(<liquid:magnesium_diboride>, <contenttweaker:blockmagnesium_diboride>);
Melting.removeRecipe(<liquid:manganese>, <contenttweaker:blockmanganese>);
Melting.removeRecipe(<liquid:manyullyn>, <contenttweaker:blockmanyullyn>);
Melting.removeRecipe(<liquid:mithril>, <contenttweaker:blockmithril>);
Melting.removeRecipe(<liquid:nickel>, <contenttweaker:blocknickel>);
Melting.removeRecipe(<liquid:nickel_silver>, <contenttweaker:blocknickel_silver>);
Melting.removeRecipe(<liquid:osmium>, <contenttweaker:blockosmium>);
Melting.removeRecipe(<liquid:platinum>, <contenttweaker:blockplatinum>);
Melting.removeRecipe(<liquid:red_alloy>, <contenttweaker:blockred_alloy>);
Melting.removeRecipe(<liquid:red_steel>, <contenttweaker:blockred_steel>);
Melting.removeRecipe(<liquid:rose_gold>, <contenttweaker:blockrose_gold>);
Melting.removeRecipe(<liquid:silver>, <contenttweaker:blocksilver>);
Melting.removeRecipe(<liquid:steel>, <contenttweaker:blocksteel>);
Melting.removeRecipe(<liquid:sterling_silver>, <contenttweaker:blocksterling_silver>);
Melting.removeRecipe(<liquid:thorium>, <contenttweaker:blockthorium>);
Melting.removeRecipe(<liquid:tin>, <contenttweaker:blocktin>);
Melting.removeRecipe(<liquid:titanium>, <contenttweaker:blocktitanium>);
Melting.removeRecipe(<liquid:tungsten>, <contenttweaker:blocktungsten>);
Melting.removeRecipe(<liquid:tungsten_steel>, <contenttweaker:blocktungsten_steel>);
Melting.removeRecipe(<liquid:uranium>, <contenttweaker:blockuranium>);
Melting.removeRecipe(<liquid:wrought_iron>, <contenttweaker:blockwrought_iron>);
Melting.removeRecipe(<liquid:zinc>, <contenttweaker:blockzinc>);
Melting.removeRecipe(<liquid:zircaloy>, <contenttweaker:blockzircaloy>);
Melting.removeRecipe(<liquid:zirconium>, <contenttweaker:blockzirconium>);

// REMOVE DRYING
Drying.removeRecipe(<minecraft:leather>);
Drying.removeRecipe(<tconstruct:edible:*>);

// SMELTERY FUEL (LAVA)
val definitionLava = <liquid:lava>.definition;
val lavaT = definitionLava.temperature;
definitionLava.temperature = 1200;

// SMELTERY FUEL (NAPALM)
val definitionNapalm = <liquid:napalm>.definition;
val napalmT = definitionNapalm.temperature;
definitionNapalm.temperature = 2760;
Fuel.registerFuel(<liquid:napalm>, 70);

// SMELTERY FUEL (GASOLINE)
val definitionGasoline = <liquid:gasoline>.definition;
val gasolineT = definitionGasoline.temperature;
definitionGasoline.temperature = 945;
Fuel.registerFuel(<liquid:gasoline>, 90);

// SMELTERY FUEL (DIESEL)
val definitionDiesel = <liquid:diesel>.definition;
val dieselT = definitionDiesel.temperature;
definitionDiesel.temperature = 2000;
Fuel.registerFuel(<liquid:diesel>, 100);

// ADD
recipes.addShaped(<conarm:travel_sack>, [[<ore:string>, <ore:leather>, <ore:string>], [<ore:rawHide>, <ore:chest>, <ore:rawHide>], [<ore:leather>, <ore:leather>, <ore:leather>]]);
recipes.addShaped(<tconstruct:seared_furnace_controller>, [[<ore:blockSeared>, <ore:blockSeared>, <ore:blockSeared>], [<tfc:bellows>, <tfc:bloomery>, <tfc:bellows>], [<ore:blockSeared>, <ore:blockSeared>, <ore:blockSeared>]]);
recipes.addShaped(<tconstruct:smeltery_controller>, [[<ore:blockSeared>, <ore:blockSeared>, <ore:blockSeared>], [<tfc:bellows>, <tfc:blast_furnace>, <tfc:bellows>], [<ore:blockSeared>, <tfc:crucible>, <ore:blockSeared>]]);
recipes.addShaped(<tconstruct:throwball:1>, [[<minecraft:flint>, <ore:dustSulfur>, <minecraft:flint>], [<ore:dustSulfur>, <minecraft:flint>, <ore:dustSulfur>], [<minecraft:flint>, <ore:dustSulfur>, <minecraft:flint>]]);
recipes.addShaped(<tconstruct:tinker_tank_controller>, [[<ore:blockSeared>, <ore:blockSeared>, <ore:blockSeared>], [<ore:blockSeared>, <minecraft:bucket>, <ore:blockSeared>], [<ore:blockSeared>, <tfc:crucible>, <ore:blockSeared>]]);
recipes.addShapeless(<tconstruct:materials:18>, [<ore:plantMoss>, <ore:plantMoss>, <ore:plantMoss>]);

recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_aluminium"}), [<tfc:metal/axe_head/aluminium>, <tfc:metal/axe_head/aluminium>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_bismuth_bronze"}), [<tfc:metal/axe_head/bismuth_bronze>, <tfc:metal/axe_head/bismuth_bronze>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_black_bronze"}), [<tfc:metal/axe_head/black_bronze>, <tfc:metal/axe_head/black_bronze>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_black_steel"}), [<tfc:metal/axe_head/black_steel>, <tfc:metal/axe_head/black_steel>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_blue_steel"}), [<tfc:metal/axe_head/blue_steel>, <tfc:metal/axe_head/blue_steel>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "bronze"}), [<tfc:metal/axe_head/bronze>, <tfc:metal/axe_head/bronze>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "cobalt"}), [<tfc:metal/axe_head/cobalt>, <tfc:metal/axe_head/cobalt>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "copper"}), [<tfc:metal/axe_head/copper>, <tfc:metal/axe_head/copper>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_invar"}), [<tfc:metal/axe_head/invar>, <tfc:metal/axe_head/invar>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "manyullyn"}), [<tfc:metal/axe_head/manyullyn>, <tfc:metal/axe_head/manyullyn>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_mithril"}), [<tfc:metal/axe_head/mithril>, <tfc:metal/axe_head/mithril>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_osmium"}), [<tfc:metal/axe_head/osmium>, <tfc:metal/axe_head/osmium>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_red_steel"}), [<tfc:metal/axe_head/red_steel>, <tfc:metal/axe_head/red_steel>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "steel"}), [<tfc:metal/axe_head/steel>, <tfc:metal/axe_head/steel>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_titanium"}), [<tfc:metal/axe_head/titanium>, <tfc:metal/axe_head/titanium>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_tungsten"}), [<tfc:metal/axe_head/tungsten>, <tfc:metal/axe_head/tungsten>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_tungsten_steel"}), [<tfc:metal/axe_head/tungsten_steel>, <tfc:metal/axe_head/tungsten_steel>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_wrought_iron"}), [<tfc:metal/axe_head/wrought_iron>, <tfc:metal/axe_head/wrought_iron>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_beryllium_copper"}), [<tfc:metal/axe_head/beryllium_copper>, <tfc:metal/axe_head/beryllium_copper>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_boron"}), [<tfc:metal/axe_head/boron>, <tfc:metal/axe_head/boron>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_nickel_silver"}), [<tfc:metal/axe_head/nickel_silver>, <tfc:metal/axe_head/nickel_silver>]);
recipes.addShapeless(<tconstruct:axe_head>.withTag({Material: "tfc_zircaloy"}), [<tfc:metal/axe_head/zircaloy>, <tfc:metal/axe_head/zircaloy>]);

recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_aluminium"}), [<tfc:metal/hammer_head/aluminium>, <tfc:metal/hammer_head/aluminium>, <tfc:metal/hammer_head/aluminium>, <tfc:metal/hammer_head/aluminium>, <tfc:metal/hammer_head/aluminium>, <tfc:metal/hammer_head/aluminium>, <tfc:metal/hammer_head/aluminium>, <tfc:metal/hammer_head/aluminium>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_bismuth_bronze"}), [<tfc:metal/hammer_head/bismuth_bronze>, <tfc:metal/hammer_head/bismuth_bronze>, <tfc:metal/hammer_head/bismuth_bronze>, <tfc:metal/hammer_head/bismuth_bronze>, <tfc:metal/hammer_head/bismuth_bronze>, <tfc:metal/hammer_head/bismuth_bronze>, <tfc:metal/hammer_head/bismuth_bronze>, <tfc:metal/hammer_head/bismuth_bronze>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_black_bronze"}), [<tfc:metal/hammer_head/black_bronze>, <tfc:metal/hammer_head/black_bronze>, <tfc:metal/hammer_head/black_bronze>, <tfc:metal/hammer_head/black_bronze>, <tfc:metal/hammer_head/black_bronze>, <tfc:metal/hammer_head/black_bronze>, <tfc:metal/hammer_head/black_bronze>, <tfc:metal/hammer_head/black_bronze>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_black_steel"}), [<tfc:metal/hammer_head/black_steel>, <tfc:metal/hammer_head/black_steel>, <tfc:metal/hammer_head/black_steel>, <tfc:metal/hammer_head/black_steel>, <tfc:metal/hammer_head/black_steel>, <tfc:metal/hammer_head/black_steel>, <tfc:metal/hammer_head/black_steel>, <tfc:metal/hammer_head/black_steel>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_blue_steel"}), [<tfc:metal/hammer_head/blue_steel>, <tfc:metal/hammer_head/blue_steel>, <tfc:metal/hammer_head/blue_steel>, <tfc:metal/hammer_head/blue_steel>, <tfc:metal/hammer_head/blue_steel>, <tfc:metal/hammer_head/blue_steel>, <tfc:metal/hammer_head/blue_steel>, <tfc:metal/hammer_head/blue_steel>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "bronze"}), [<tfc:metal/hammer_head/bronze>, <tfc:metal/hammer_head/bronze>, <tfc:metal/hammer_head/bronze>, <tfc:metal/hammer_head/bronze>, <tfc:metal/hammer_head/bronze>, <tfc:metal/hammer_head/bronze>, <tfc:metal/hammer_head/bronze>, <tfc:metal/hammer_head/bronze>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "cobalt"}), [<tfc:metal/hammer_head/cobalt>, <tfc:metal/hammer_head/cobalt>, <tfc:metal/hammer_head/cobalt>, <tfc:metal/hammer_head/cobalt>, <tfc:metal/hammer_head/cobalt>, <tfc:metal/hammer_head/cobalt>, <tfc:metal/hammer_head/cobalt>, <tfc:metal/hammer_head/cobalt>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "copper"}), [<tfc:metal/hammer_head/copper>, <tfc:metal/hammer_head/copper>, <tfc:metal/hammer_head/copper>, <tfc:metal/hammer_head/copper>, <tfc:metal/hammer_head/copper>, <tfc:metal/hammer_head/copper>, <tfc:metal/hammer_head/copper>, <tfc:metal/hammer_head/copper>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_invar"}), [<tfc:metal/hammer_head/invar>, <tfc:metal/hammer_head/invar>, <tfc:metal/hammer_head/invar>, <tfc:metal/hammer_head/invar>, <tfc:metal/hammer_head/invar>, <tfc:metal/hammer_head/invar>, <tfc:metal/hammer_head/invar>, <tfc:metal/hammer_head/invar>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "manyullyn"}), [<tfc:metal/hammer_head/manyullyn>, <tfc:metal/hammer_head/manyullyn>, <tfc:metal/hammer_head/manyullyn>, <tfc:metal/hammer_head/manyullyn>, <tfc:metal/hammer_head/manyullyn>, <tfc:metal/hammer_head/manyullyn>, <tfc:metal/hammer_head/manyullyn>, <tfc:metal/hammer_head/manyullyn>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_mithril"}), [<tfc:metal/hammer_head/mithril>, <tfc:metal/hammer_head/mithril>, <tfc:metal/hammer_head/mithril>, <tfc:metal/hammer_head/mithril>, <tfc:metal/hammer_head/mithril>, <tfc:metal/hammer_head/mithril>, <tfc:metal/hammer_head/mithril>, <tfc:metal/hammer_head/mithril>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_osmium"}), [<tfc:metal/hammer_head/osmium>, <tfc:metal/hammer_head/osmium>, <tfc:metal/hammer_head/osmium>, <tfc:metal/hammer_head/osmium>, <tfc:metal/hammer_head/osmium>, <tfc:metal/hammer_head/osmium>, <tfc:metal/hammer_head/osmium>, <tfc:metal/hammer_head/osmium>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_red_steel"}), [<tfc:metal/hammer_head/red_steel>, <tfc:metal/hammer_head/red_steel>, <tfc:metal/hammer_head/red_steel>, <tfc:metal/hammer_head/red_steel>, <tfc:metal/hammer_head/red_steel>, <tfc:metal/hammer_head/red_steel>, <tfc:metal/hammer_head/red_steel>, <tfc:metal/hammer_head/red_steel>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "steel"}), [<tfc:metal/hammer_head/steel>, <tfc:metal/hammer_head/steel>, <tfc:metal/hammer_head/steel>, <tfc:metal/hammer_head/steel>, <tfc:metal/hammer_head/steel>, <tfc:metal/hammer_head/steel>, <tfc:metal/hammer_head/steel>, <tfc:metal/hammer_head/steel>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_titanium"}), [<tfc:metal/hammer_head/titanium>, <tfc:metal/hammer_head/titanium>, <tfc:metal/hammer_head/titanium>, <tfc:metal/hammer_head/titanium>, <tfc:metal/hammer_head/titanium>, <tfc:metal/hammer_head/titanium>, <tfc:metal/hammer_head/titanium>, <tfc:metal/hammer_head/titanium>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_tungsten"}), [<tfc:metal/hammer_head/tungsten>, <tfc:metal/hammer_head/tungsten>, <tfc:metal/hammer_head/tungsten>, <tfc:metal/hammer_head/tungsten>, <tfc:metal/hammer_head/tungsten>, <tfc:metal/hammer_head/tungsten>, <tfc:metal/hammer_head/tungsten>, <tfc:metal/hammer_head/tungsten>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_tungsten_steel"}), [<tfc:metal/hammer_head/tungsten_steel>, <tfc:metal/hammer_head/tungsten_steel>, <tfc:metal/hammer_head/tungsten_steel>, <tfc:metal/hammer_head/tungsten_steel>, <tfc:metal/hammer_head/tungsten_steel>, <tfc:metal/hammer_head/tungsten_steel>, <tfc:metal/hammer_head/tungsten_steel>, <tfc:metal/hammer_head/tungsten_steel>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_wrought_iron"}), [<tfc:metal/hammer_head/wrought_iron>, <tfc:metal/hammer_head/wrought_iron>, <tfc:metal/hammer_head/wrought_iron>, <tfc:metal/hammer_head/wrought_iron>, <tfc:metal/hammer_head/wrought_iron>, <tfc:metal/hammer_head/wrought_iron>, <tfc:metal/hammer_head/wrought_iron>, <tfc:metal/hammer_head/wrought_iron>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_beryllium_copper"}), [<tfc:metal/hammer_head/beryllium_copper>, <tfc:metal/hammer_head/beryllium_copper>, <tfc:metal/hammer_head/beryllium_copper>, <tfc:metal/hammer_head/beryllium_copper>, <tfc:metal/hammer_head/beryllium_copper>, <tfc:metal/hammer_head/beryllium_copper>, <tfc:metal/hammer_head/beryllium_copper>, <tfc:metal/hammer_head/beryllium_copper>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_boron"}), [<tfc:metal/hammer_head/boron>, <tfc:metal/hammer_head/boron>, <tfc:metal/hammer_head/boron>, <tfc:metal/hammer_head/boron>, <tfc:metal/hammer_head/boron>, <tfc:metal/hammer_head/boron>, <tfc:metal/hammer_head/boron>, <tfc:metal/hammer_head/boron>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_nickel_silver"}), [<tfc:metal/hammer_head/nickel_silver>, <tfc:metal/hammer_head/nickel_silver>, <tfc:metal/hammer_head/nickel_silver>, <tfc:metal/hammer_head/nickel_silver>, <tfc:metal/hammer_head/nickel_silver>, <tfc:metal/hammer_head/nickel_silver>, <tfc:metal/hammer_head/nickel_silver>, <tfc:metal/hammer_head/nickel_silver>]);
recipes.addShapeless(<tconstruct:hammer_head>.withTag({Material: "tfc_zircaloy"}), [<tfc:metal/hammer_head/zircaloy>, <tfc:metal/hammer_head/zircaloy>, <tfc:metal/hammer_head/zircaloy>, <tfc:metal/hammer_head/zircaloy>, <tfc:metal/hammer_head/zircaloy>, <tfc:metal/hammer_head/zircaloy>, <tfc:metal/hammer_head/zircaloy>, <tfc:metal/hammer_head/zircaloy>]);

recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_aluminium"}), [<tfc:metal/knife_blade/aluminium>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_bismuth_bronze"}), [<tfc:metal/knife_blade/bismuth_bronze>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_black_bronze"}), [<tfc:metal/knife_blade/black_bronze>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_black_steel"}), [<tfc:metal/knife_blade/black_steel>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_blue_steel"}), [<tfc:metal/knife_blade/blue_steel>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "bronze"}), [<tfc:metal/knife_blade/bronze>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "cobalt"}), [<tfc:metal/knife_blade/cobalt>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "copper"}), [<tfc:metal/knife_blade/copper>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_invar"}), [<tfc:metal/knife_blade/invar>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "manyullyn"}), [<tfc:metal/knife_blade/manyullyn>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_mithril"}), [<tfc:metal/knife_blade/mithril>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_osmium"}), [<tfc:metal/knife_blade/osmium>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_red_steel"}), [<tfc:metal/knife_blade/red_steel>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "steel"}), [<tfc:metal/knife_blade/steel>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_titanium"}), [<tfc:metal/knife_blade/titanium>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_tungsten"}), [<tfc:metal/knife_blade/tungsten>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_tungsten_steel"}), [<tfc:metal/knife_blade/tungsten_steel>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_wrought_iron"}), [<tfc:metal/knife_blade/wrought_iron>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_beryllium_copper"}), [<tfc:metal/knife_blade/beryllium_copper>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_boron"}), [<tfc:metal/knife_blade/boron>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_nickel_silver"}), [<tfc:metal/knife_blade/nickel_silver>]);
recipes.addShapeless(<tconstruct:knife_blade>.withTag({Material: "tfc_zircaloy"}), [<tfc:metal/knife_blade/zircaloy>]);

recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_aluminium"}), [<tfc:metal/pick_head/aluminium>, <tfc:metal/pick_head/aluminium>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_bismuth_bronze"}), [<tfc:metal/pick_head/bismuth_bronze>, <tfc:metal/pick_head/bismuth_bronze>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_black_bronze"}), [<tfc:metal/pick_head/black_bronze>, <tfc:metal/pick_head/black_bronze>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_black_steel"}), [<tfc:metal/pick_head/black_steel>, <tfc:metal/pick_head/black_steel>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_blue_steel"}), [<tfc:metal/pick_head/blue_steel>, <tfc:metal/pick_head/blue_steel>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "bronze"}), [<tfc:metal/pick_head/bronze>, <tfc:metal/pick_head/bronze>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "cobalt"}), [<tfc:metal/pick_head/cobalt>, <tfc:metal/pick_head/cobalt>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "copper"}), [<tfc:metal/pick_head/copper>, <tfc:metal/pick_head/copper>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_invar"}), [<tfc:metal/pick_head/invar>, <tfc:metal/pick_head/invar>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "manyullyn"}), [<tfc:metal/pick_head/manyullyn>, <tfc:metal/pick_head/manyullyn>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_mithril"}), [<tfc:metal/pick_head/mithril>, <tfc:metal/pick_head/mithril>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_osmium"}), [<tfc:metal/pick_head/osmium>, <tfc:metal/pick_head/osmium>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_red_steel"}), [<tfc:metal/pick_head/red_steel>, <tfc:metal/pick_head/red_steel>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "steel"}), [<tfc:metal/pick_head/steel>, <tfc:metal/pick_head/steel>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_titanium"}), [<tfc:metal/pick_head/titanium>, <tfc:metal/pick_head/titanium>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_tungsten"}), [<tfc:metal/pick_head/tungsten>, <tfc:metal/pick_head/tungsten>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_tungsten_steel"}), [<tfc:metal/pick_head/tungsten_steel>, <tfc:metal/pick_head/tungsten_steel>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_wrought_iron"}), [<tfc:metal/pick_head/wrought_iron>, <tfc:metal/pick_head/wrought_iron>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_beryllium_copper"}), [<tfc:metal/pick_head/beryllium_copper>, <tfc:metal/pick_head/beryllium_copper>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_boron"}), [<tfc:metal/pick_head/boron>, <tfc:metal/pick_head/boron>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_nickel_silver"}), [<tfc:metal/pick_head/nickel_silver>, <tfc:metal/pick_head/nickel_silver>]);
recipes.addShapeless(<tconstruct:pick_head>.withTag({Material: "tfc_zircaloy"}), [<tfc:metal/pick_head/zircaloy>, <tfc:metal/pick_head/zircaloy>]);

recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_aluminium"}), [<tfc:metal/propick_head/aluminium>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_bismuth_bronze"}), [<tfc:metal/propick_head/bismuth_bronze>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_black_bronze"}), [<tfc:metal/propick_head/black_bronze>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_black_steel"}), [<tfc:metal/propick_head/black_steel>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_blue_steel"}), [<tfc:metal/propick_head/blue_steel>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "bronze"}), [<tfc:metal/propick_head/bronze>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "cobalt"}), [<tfc:metal/propick_head/cobalt>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "copper"}), [<tfc:metal/propick_head/copper>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_invar"}), [<tfc:metal/propick_head/invar>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "manyullyn"}), [<tfc:metal/propick_head/manyullyn>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_mithril"}), [<tfc:metal/propick_head/mithril>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_osmium"}), [<tfc:metal/propick_head/osmium>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_red_steel"}), [<tfc:metal/propick_head/red_steel>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "steel"}), [<tfc:metal/propick_head/steel>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_titanium"}), [<tfc:metal/propick_head/titanium>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_tungsten"}), [<tfc:metal/propick_head/tungsten>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_tungsten_steel"}), [<tfc:metal/propick_head/tungsten_steel>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_wrought_iron"}), [<tfc:metal/propick_head/wrought_iron>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_beryllium_copper"}), [<tfc:metal/propick_head/beryllium_copper>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_boron"}), [<tfc:metal/propick_head/boron>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_nickel_silver"}), [<tfc:metal/propick_head/nickel_silver>]);
recipes.addShapeless(<tfc_tinker:propick_head>.withTag({Material: "tfc_zircaloy"}), [<tfc:metal/propick_head/zircaloy>]);

recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_aluminium"}), [<tfc:metal/scythe_blade/aluminium>, <tfc:metal/scythe_blade/aluminium>, <tfc:metal/scythe_blade/aluminium>, <tfc:metal/scythe_blade/aluminium>, <tfc:metal/scythe_blade/aluminium>, <tfc:metal/scythe_blade/aluminium>, <tfc:metal/scythe_blade/aluminium>, <tfc:metal/scythe_blade/aluminium>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_bismuth_bronze"}), [<tfc:metal/scythe_blade/bismuth_bronze>, <tfc:metal/scythe_blade/bismuth_bronze>, <tfc:metal/scythe_blade/bismuth_bronze>, <tfc:metal/scythe_blade/bismuth_bronze>, <tfc:metal/scythe_blade/bismuth_bronze>, <tfc:metal/scythe_blade/bismuth_bronze>, <tfc:metal/scythe_blade/bismuth_bronze>, <tfc:metal/scythe_blade/bismuth_bronze>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_black_bronze"}), [<tfc:metal/scythe_blade/black_bronze>, <tfc:metal/scythe_blade/black_bronze>, <tfc:metal/scythe_blade/black_bronze>, <tfc:metal/scythe_blade/black_bronze>, <tfc:metal/scythe_blade/black_bronze>, <tfc:metal/scythe_blade/black_bronze>, <tfc:metal/scythe_blade/black_bronze>, <tfc:metal/scythe_blade/black_bronze>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_black_steel"}), [<tfc:metal/scythe_blade/black_steel>, <tfc:metal/scythe_blade/black_steel>, <tfc:metal/scythe_blade/black_steel>, <tfc:metal/scythe_blade/black_steel>, <tfc:metal/scythe_blade/black_steel>, <tfc:metal/scythe_blade/black_steel>, <tfc:metal/scythe_blade/black_steel>, <tfc:metal/scythe_blade/black_steel>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_blue_steel"}), [<tfc:metal/scythe_blade/blue_steel>, <tfc:metal/scythe_blade/blue_steel>, <tfc:metal/scythe_blade/blue_steel>, <tfc:metal/scythe_blade/blue_steel>, <tfc:metal/scythe_blade/blue_steel>, <tfc:metal/scythe_blade/blue_steel>, <tfc:metal/scythe_blade/blue_steel>, <tfc:metal/scythe_blade/blue_steel>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "bronze"}), [<tfc:metal/scythe_blade/bronze>, <tfc:metal/scythe_blade/bronze>, <tfc:metal/scythe_blade/bronze>, <tfc:metal/scythe_blade/bronze>, <tfc:metal/scythe_blade/bronze>, <tfc:metal/scythe_blade/bronze>, <tfc:metal/scythe_blade/bronze>, <tfc:metal/scythe_blade/bronze>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "cobalt"}), [<tfc:metal/scythe_blade/cobalt>, <tfc:metal/scythe_blade/cobalt>, <tfc:metal/scythe_blade/cobalt>, <tfc:metal/scythe_blade/cobalt>, <tfc:metal/scythe_blade/cobalt>, <tfc:metal/scythe_blade/cobalt>, <tfc:metal/scythe_blade/cobalt>, <tfc:metal/scythe_blade/cobalt>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "copper"}), [<tfc:metal/scythe_blade/copper>, <tfc:metal/scythe_blade/copper>, <tfc:metal/scythe_blade/copper>, <tfc:metal/scythe_blade/copper>, <tfc:metal/scythe_blade/copper>, <tfc:metal/scythe_blade/copper>, <tfc:metal/scythe_blade/copper>, <tfc:metal/scythe_blade/copper>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_invar"}), [<tfc:metal/scythe_blade/invar>, <tfc:metal/scythe_blade/invar>, <tfc:metal/scythe_blade/invar>, <tfc:metal/scythe_blade/invar>, <tfc:metal/scythe_blade/invar>, <tfc:metal/scythe_blade/invar>, <tfc:metal/scythe_blade/invar>, <tfc:metal/scythe_blade/invar>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "manyullyn"}), [<tfc:metal/scythe_blade/manyullyn>, <tfc:metal/scythe_blade/manyullyn>, <tfc:metal/scythe_blade/manyullyn>, <tfc:metal/scythe_blade/manyullyn>, <tfc:metal/scythe_blade/manyullyn>, <tfc:metal/scythe_blade/manyullyn>, <tfc:metal/scythe_blade/manyullyn>, <tfc:metal/scythe_blade/manyullyn>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_mithril"}), [<tfc:metal/scythe_blade/mithril>, <tfc:metal/scythe_blade/mithril>, <tfc:metal/scythe_blade/mithril>, <tfc:metal/scythe_blade/mithril>, <tfc:metal/scythe_blade/mithril>, <tfc:metal/scythe_blade/mithril>, <tfc:metal/scythe_blade/mithril>, <tfc:metal/scythe_blade/mithril>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_osmium"}), [<tfc:metal/scythe_blade/osmium>, <tfc:metal/scythe_blade/osmium>, <tfc:metal/scythe_blade/osmium>, <tfc:metal/scythe_blade/osmium>, <tfc:metal/scythe_blade/osmium>, <tfc:metal/scythe_blade/osmium>, <tfc:metal/scythe_blade/osmium>, <tfc:metal/scythe_blade/osmium>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_red_steel"}), [<tfc:metal/scythe_blade/red_steel>, <tfc:metal/scythe_blade/red_steel>, <tfc:metal/scythe_blade/red_steel>, <tfc:metal/scythe_blade/red_steel>, <tfc:metal/scythe_blade/red_steel>, <tfc:metal/scythe_blade/red_steel>, <tfc:metal/scythe_blade/red_steel>, <tfc:metal/scythe_blade/red_steel>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "steel"}), [<tfc:metal/scythe_blade/steel>, <tfc:metal/scythe_blade/steel>, <tfc:metal/scythe_blade/steel>, <tfc:metal/scythe_blade/steel>, <tfc:metal/scythe_blade/steel>, <tfc:metal/scythe_blade/steel>, <tfc:metal/scythe_blade/steel>, <tfc:metal/scythe_blade/steel>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_titanium"}), [<tfc:metal/scythe_blade/titanium>, <tfc:metal/scythe_blade/titanium>, <tfc:metal/scythe_blade/titanium>, <tfc:metal/scythe_blade/titanium>, <tfc:metal/scythe_blade/titanium>, <tfc:metal/scythe_blade/titanium>, <tfc:metal/scythe_blade/titanium>, <tfc:metal/scythe_blade/titanium>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_tungsten"}), [<tfc:metal/scythe_blade/tungsten>, <tfc:metal/scythe_blade/tungsten>, <tfc:metal/scythe_blade/tungsten>, <tfc:metal/scythe_blade/tungsten>, <tfc:metal/scythe_blade/tungsten>, <tfc:metal/scythe_blade/tungsten>, <tfc:metal/scythe_blade/tungsten>, <tfc:metal/scythe_blade/tungsten>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_tungsten_steel"}), [<tfc:metal/scythe_blade/tungsten_steel>, <tfc:metal/scythe_blade/tungsten_steel>, <tfc:metal/scythe_blade/tungsten_steel>, <tfc:metal/scythe_blade/tungsten_steel>, <tfc:metal/scythe_blade/tungsten_steel>, <tfc:metal/scythe_blade/tungsten_steel>, <tfc:metal/scythe_blade/tungsten_steel>, <tfc:metal/scythe_blade/tungsten_steel>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_wrought_iron"}), [<tfc:metal/scythe_blade/wrought_iron>, <tfc:metal/scythe_blade/wrought_iron>, <tfc:metal/scythe_blade/wrought_iron>, <tfc:metal/scythe_blade/wrought_iron>, <tfc:metal/scythe_blade/wrought_iron>, <tfc:metal/scythe_blade/wrought_iron>, <tfc:metal/scythe_blade/wrought_iron>, <tfc:metal/scythe_blade/wrought_iron>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_beryllium_copper"}), [<tfc:metal/scythe_blade/beryllium_copper>, <tfc:metal/scythe_blade/beryllium_copper>, <tfc:metal/scythe_blade/beryllium_copper>, <tfc:metal/scythe_blade/beryllium_copper>, <tfc:metal/scythe_blade/beryllium_copper>, <tfc:metal/scythe_blade/beryllium_copper>, <tfc:metal/scythe_blade/beryllium_copper>, <tfc:metal/scythe_blade/beryllium_copper>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_boron"}), [<tfc:metal/scythe_blade/boron>, <tfc:metal/scythe_blade/boron>, <tfc:metal/scythe_blade/boron>, <tfc:metal/scythe_blade/boron>, <tfc:metal/scythe_blade/boron>, <tfc:metal/scythe_blade/boron>, <tfc:metal/scythe_blade/boron>, <tfc:metal/scythe_blade/boron>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_nickel_silver"}), [<tfc:metal/scythe_blade/nickel_silver>, <tfc:metal/scythe_blade/nickel_silver>, <tfc:metal/scythe_blade/nickel_silver>, <tfc:metal/scythe_blade/nickel_silver>, <tfc:metal/scythe_blade/nickel_silver>, <tfc:metal/scythe_blade/nickel_silver>, <tfc:metal/scythe_blade/nickel_silver>, <tfc:metal/scythe_blade/nickel_silver>]);
recipes.addShapeless(<tconstruct:scythe_head>.withTag({Material: "tfc_zircaloy"}), [<tfc:metal/scythe_blade/zircaloy>, <tfc:metal/scythe_blade/zircaloy>, <tfc:metal/scythe_blade/zircaloy>, <tfc:metal/scythe_blade/zircaloy>, <tfc:metal/scythe_blade/zircaloy>, <tfc:metal/scythe_blade/zircaloy>, <tfc:metal/scythe_blade/zircaloy>, <tfc:metal/scythe_blade/zircaloy>]);

recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_aluminium"}), [<tfc:metal/shovel_head/aluminium>, <tfc:metal/shovel_head/aluminium>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_bismuth_bronze"}), [<tfc:metal/shovel_head/bismuth_bronze>, <tfc:metal/shovel_head/bismuth_bronze>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_black_bronze"}), [<tfc:metal/shovel_head/black_bronze>, <tfc:metal/shovel_head/black_bronze>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_black_steel"}), [<tfc:metal/shovel_head/black_steel>, <tfc:metal/shovel_head/black_steel>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_blue_steel"}), [<tfc:metal/shovel_head/blue_steel>, <tfc:metal/shovel_head/blue_steel>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "bronze"}), [<tfc:metal/shovel_head/bronze>, <tfc:metal/shovel_head/bronze>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "cobalt"}), [<tfc:metal/shovel_head/cobalt>, <tfc:metal/shovel_head/cobalt>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "copper"}), [<tfc:metal/shovel_head/copper>, <tfc:metal/shovel_head/copper>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_invar"}), [<tfc:metal/shovel_head/invar>, <tfc:metal/shovel_head/invar>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "manyullyn"}), [<tfc:metal/shovel_head/manyullyn>, <tfc:metal/shovel_head/manyullyn>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_mithril"}), [<tfc:metal/shovel_head/mithril>, <tfc:metal/shovel_head/mithril>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_osmium"}), [<tfc:metal/shovel_head/osmium>, <tfc:metal/shovel_head/osmium>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_red_steel"}), [<tfc:metal/shovel_head/red_steel>, <tfc:metal/shovel_head/red_steel>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "steel"}), [<tfc:metal/shovel_head/steel>, <tfc:metal/shovel_head/steel>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_titanium"}), [<tfc:metal/shovel_head/titanium>, <tfc:metal/shovel_head/titanium>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_tungsten"}), [<tfc:metal/shovel_head/tungsten>, <tfc:metal/shovel_head/tungsten>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_tungsten_steel"}), [<tfc:metal/shovel_head/tungsten_steel>, <tfc:metal/shovel_head/tungsten_steel>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_wrought_iron"}), [<tfc:metal/shovel_head/wrought_iron>, <tfc:metal/shovel_head/wrought_iron>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_beryllium_copper"}), [<tfc:metal/shovel_head/beryllium_copper>, <tfc:metal/shovel_head/beryllium_copper>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_boron"}), [<tfc:metal/shovel_head/boron>, <tfc:metal/shovel_head/boron>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_nickel_silver"}), [<tfc:metal/shovel_head/nickel_silver>, <tfc:metal/shovel_head/nickel_silver>]);
recipes.addShapeless(<tconstruct:shovel_head>.withTag({Material: "tfc_zircaloy"}), [<tfc:metal/shovel_head/zircaloy>, <tfc:metal/shovel_head/zircaloy>]);

recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_aluminium"}), [<tfc:metal/sword_blade/aluminium>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_bismuth_bronze"}), [<tfc:metal/sword_blade/bismuth_bronze>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_black_bronze"}), [<tfc:metal/sword_blade/black_bronze>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_black_steel"}), [<tfc:metal/sword_blade/black_steel>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_blue_steel"}), [<tfc:metal/sword_blade/blue_steel>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "bronze"}), [<tfc:metal/sword_blade/bronze>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "cobalt"}), [<tfc:metal/sword_blade/cobalt>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "copper"}), [<tfc:metal/sword_blade/copper>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_invar"}), [<tfc:metal/sword_blade/invar>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "manyullyn"}), [<tfc:metal/sword_blade/manyullyn>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_mithril"}), [<tfc:metal/sword_blade/mithril>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_osmium"}), [<tfc:metal/sword_blade/osmium>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_red_steel"}), [<tfc:metal/sword_blade/red_steel>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "steel"}), [<tfc:metal/sword_blade/steel>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_titanium"}), [<tfc:metal/sword_blade/titanium>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_tungsten"}), [<tfc:metal/sword_blade/tungsten>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_tungsten_steel"}), [<tfc:metal/sword_blade/tungsten_steel>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_wrought_iron"}), [<tfc:metal/sword_blade/wrought_iron>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_beryllium_copper"}), [<tfc:metal/sword_blade/beryllium_copper>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_boron"}), [<tfc:metal/sword_blade/boron>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_nickel_silver"}), [<tfc:metal/sword_blade/nickel_silver>]);
recipes.addShapeless(<tconstruct:sword_blade>.withTag({Material: "tfc_zircaloy"}), [<tfc:metal/sword_blade/zircaloy>]);

// ADD ALLOY
Alloy.addRecipe(<liquid:bismuth_bronze> * 5, [<liquid:brass> * 4, <liquid:bismuth> * 1]);
Alloy.addRecipe(<liquid:black_bronze> * 5, [<liquid:electrum> * 2, <liquid:copper> * 3]);
Alloy.addRecipe(<liquid:black_steel> * 2, [<liquid:pig_iron> * 1, <liquid:steel> * 1]);
Alloy.addRecipe(<liquid:black_steel> * 2, [<liquid:pigiron> * 1, <liquid:steel> * 1]);
Alloy.addRecipe(<liquid:mithril> * 10, [<liquid:copper> * 9, <liquid:antimony> * 1]);
Alloy.addRecipe(<liquid:tungsten_steel> * 9, [<liquid:tungsten> * 1, <liquid:steel> * 8]);

// ADD CASTING
Casting.addBasinRecipe(<contenttweaker:blockaluminium>, null, <liquid:aluminium>, 800);
Casting.addBasinRecipe(<contenttweaker:blockaluminium_brass>, null, <liquid:aluminium_brass>, 800);
Casting.addBasinRecipe(<contenttweaker:blockantimony>, null, <liquid:antimony>, 800);
Casting.addBasinRecipe(<contenttweaker:blockardite>, null, <liquid:ardite>, 800);
Casting.addBasinRecipe(<contenttweaker:blockberyllium>, null, <liquid:beryllium>, 800);
Casting.addBasinRecipe(<contenttweaker:blockberyllium_copper>, null, <liquid:beryllium_copper>, 800);
Casting.addBasinRecipe(<contenttweaker:blockbismuth>, null, <liquid:bismuth>, 800);
Casting.addBasinRecipe(<contenttweaker:blockbismuth_bronze>, null, <liquid:bismuth_bronze>, 800);
Casting.addBasinRecipe(<contenttweaker:blockblack_bronze>, null, <liquid:black_bronze>, 800);
Casting.addBasinRecipe(<contenttweaker:blockblack_steel>, null, <liquid:black_steel>, 800);
Casting.addBasinRecipe(<contenttweaker:blockblue_steel>, null, <liquid:blue_steel>, 800);
Casting.addBasinRecipe(<contenttweaker:blockboron>, null, <liquid:boron>, 800);
Casting.addBasinRecipe(<contenttweaker:blockbrass>, null, <liquid:brass>, 800);
Casting.addBasinRecipe(<contenttweaker:blockbronze>, null, <liquid:bronze>, 800);
Casting.addBasinRecipe(<contenttweaker:blockcobalt>, null, <liquid:cobalt>, 800);
Casting.addBasinRecipe(<contenttweaker:blockconstantan>, null, <liquid:constantan>, 800);
Casting.addBasinRecipe(<contenttweaker:blockcopper>, null, <liquid:copper>, 800);
Casting.addBasinRecipe(<contenttweaker:blockelectrum>, null, <liquid:electrum>, 800);
Casting.addBasinRecipe(<contenttweaker:blockferroboron>, null, <liquid:ferroboron>, 800);
Casting.addBasinRecipe(<contenttweaker:blockgold>, null, <liquid:gold>, 800);
Casting.addBasinRecipe(<contenttweaker:blockhsla_steel>, null, <liquid:hsla_steel>, 800);
Casting.addBasinRecipe(<contenttweaker:blockinvar>, null, <liquid:invar>, 800);
Casting.addBasinRecipe(<contenttweaker:blocklead>, null, <liquid:lead>, 800);
Casting.addBasinRecipe(<contenttweaker:blocklithium>, null, <liquid:lithium>, 800);
Casting.addBasinRecipe(<contenttweaker:blockmagnesium>, null, <liquid:magnesium>, 800);
Casting.addBasinRecipe(<contenttweaker:blockmagnesium_diboride>, null, <liquid:magnesium_diboride>, 800);
Casting.addBasinRecipe(<contenttweaker:blockmanganese>, null, <liquid:manganese>, 800);
Casting.addBasinRecipe(<contenttweaker:blockmanyullyn>, null, <liquid:manyullyn>, 800);
Casting.addBasinRecipe(<contenttweaker:blockmithril>, null, <liquid:mithril>, 800);
Casting.addBasinRecipe(<contenttweaker:blocknickel>, null, <liquid:nickel>, 800);
Casting.addBasinRecipe(<contenttweaker:blocknickel_silver>, null, <liquid:nickel_silver>, 800);
Casting.addBasinRecipe(<contenttweaker:blockosmium>, null, <liquid:osmium>, 800);
Casting.addBasinRecipe(<contenttweaker:blockplatinum>, null, <liquid:platinum>, 800);
Casting.addBasinRecipe(<contenttweaker:blockred_alloy>, null, <liquid:red_alloy>, 800);
Casting.addBasinRecipe(<contenttweaker:blockred_steel>, null, <liquid:red_steel>, 800);
Casting.addBasinRecipe(<contenttweaker:blockrose_gold>, null, <liquid:rose_gold>, 800);
Casting.addBasinRecipe(<contenttweaker:blocksilver>, null, <liquid:silver>, 800);
Casting.addBasinRecipe(<contenttweaker:blocksteel>, null, <liquid:steel>, 800);
Casting.addBasinRecipe(<contenttweaker:blocksterling_silver>, null, <liquid:sterling_silver>, 800);
Casting.addBasinRecipe(<contenttweaker:blockthorium>, null, <liquid:thorium>, 800);
Casting.addBasinRecipe(<contenttweaker:blocktin>, null, <liquid:tin>, 800);
Casting.addBasinRecipe(<contenttweaker:blocktitanium>, null, <liquid:titanium>, 800);
Casting.addBasinRecipe(<contenttweaker:blocktungsten>, null, <liquid:tungsten>, 800);
Casting.addBasinRecipe(<contenttweaker:blocktungsten_steel>, null, <liquid:tungsten_steel>, 800);
Casting.addBasinRecipe(<contenttweaker:blockuranium>, null, <liquid:uranium>, 800);
Casting.addBasinRecipe(<contenttweaker:blockwrought_iron>, null, <liquid:wrought_iron>, 800);
Casting.addBasinRecipe(<contenttweaker:blockzinc>, null, <liquid:zinc>, 800);
Casting.addBasinRecipe(<contenttweaker:blockzircaloy>, null, <liquid:zircaloy>, 800);
Casting.addBasinRecipe(<contenttweaker:blockzirconium>, null, <liquid:zirconium>, 800);

Casting.addTableRecipe(<minecraft:golden_apple:0>, <ore:apple>, <liquid:gold>, 800, true, 2000);
Casting.addTableRecipe(<minecraft:golden_carrot>, <ore:carrot>, <liquid:gold>, 800, true, 2000);

Casting.addTableRecipe(<tfc:metal/axe_head/aluminium>, <tfc:ceramics/fired/mold/axe_head>, <liquid:aluminium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/bismuth_bronze>, <tfc:ceramics/fired/mold/axe_head>, <liquid:bismuth_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/black_bronze>, <tfc:ceramics/fired/mold/axe_head>, <liquid:black_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/black_steel>, <tfc:ceramics/fired/mold/axe_head>, <liquid:black_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/blue_steel>, <tfc:ceramics/fired/mold/axe_head>, <liquid:blue_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/bronze>, <tfc:ceramics/fired/mold/axe_head>, <liquid:bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/cobalt>, <tfc:ceramics/fired/mold/axe_head>, <liquid:cobalt>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/copper>, <tfc:ceramics/fired/mold/axe_head>, <liquid:copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/invar>, <tfc:ceramics/fired/mold/axe_head>, <liquid:invar>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/manyullyn>, <tfc:ceramics/fired/mold/axe_head>, <liquid:manyullyn>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/mithril>, <tfc:ceramics/fired/mold/axe_head>, <liquid:mithril>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/osmium>, <tfc:ceramics/fired/mold/axe_head>, <liquid:osmium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/red_steel>, <tfc:ceramics/fired/mold/axe_head>, <liquid:red_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/steel>, <tfc:ceramics/fired/mold/axe_head>, <liquid:steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/titanium>, <tfc:ceramics/fired/mold/axe_head>, <liquid:titanium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/tungsten>, <tfc:ceramics/fired/mold/axe_head>, <liquid:tungsten>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/tungsten_steel>, <tfc:ceramics/fired/mold/axe_head>, <liquid:tungsten_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/wrought_iron>, <tfc:ceramics/fired/mold/axe_head>, <liquid:wrought_iron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/beryllium_copper>, <tfc:ceramics/fired/mold/axe_head>, <liquid:beryllium_copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/boron>, <tfc:ceramics/fired/mold/axe_head>, <liquid:boron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/nickel_silver>, <tfc:ceramics/fired/mold/axe_head>, <liquid:nickel_silver>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/axe_head/zircaloy>, <tfc:ceramics/fired/mold/axe_head>, <liquid:zircaloy>, 100, false, 40);

Casting.addTableRecipe(<tfc:metal/chisel_head/aluminium>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:aluminium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/bismuth_bronze>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:bismuth_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/black_bronze>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:black_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/black_steel>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:black_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/blue_steel>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:blue_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/bronze>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/cobalt>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:cobalt>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/copper>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/invar>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:invar>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/manyullyn>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:manyullyn>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/mithril>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:mithril>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/osmium>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:osmium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/red_steel>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:red_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/steel>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/titanium>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:titanium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/tungsten>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:tungsten>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/tungsten_steel>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:tungsten_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/wrought_iron>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:wrought_iron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/beryllium_copper>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:wrought_iron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/boron>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:wrought_iron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/nickel_silver>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:wrought_iron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/chisel_head/zircaloy>, <tfc:ceramics/fired/mold/chisel_head>, <liquid:wrought_iron>, 100, false, 40);

Casting.addTableRecipe(<tfc:metal/hammer_head/aluminium>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:aluminium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/bismuth_bronze>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:bismuth_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/black_bronze>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:black_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/black_steel>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:black_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/blue_steel>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:blue_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/bronze>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/cobalt>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:cobalt>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/copper>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/invar>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:invar>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/manyullyn>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:manyullyn>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/mithril>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:mithril>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/osmium>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:osmium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/red_steel>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:red_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/steel>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/titanium>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:titanium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/tungsten>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:tungsten>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/tungsten_steel>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:tungsten_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/wrought_iron>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:wrought_iron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/beryllium_copper>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:beryllium_copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/boron>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:boron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/nickel_silver>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:nickel_silver>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hammer_head/zircaloy>, <tfc:ceramics/fired/mold/hammer_head>, <liquid:zircaloy>, 100, false, 40);

Casting.addTableRecipe(<tfc:metal/hoe_head/aluminium>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:aluminium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/bismuth_bronze>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:bismuth_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/black_bronze>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:black_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/black_steel>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:black_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/blue_steel>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:blue_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/bronze>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/cobalt>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:cobalt>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/copper>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/invar>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:invar>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/manyullyn>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:manyullyn>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/mithril>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:mithril>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/osmium>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:osmium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/red_steel>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:red_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/steel>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/titanium>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:titanium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/tungsten>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:tungsten>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/tungsten_steel>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:tungsten_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/wrought_iron>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:wrought_iron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/beryllium_copper>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:beryllium_copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/boron>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:boron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/nickel_silver>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:nickel_silver>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/hoe_head/zircaloy>, <tfc:ceramics/fired/mold/hoe_head>, <liquid:zircaloy>, 100, false, 40);

Casting.addTableRecipe(<tfc:metal/javelin_head/aluminium>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:aluminium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/bismuth_bronze>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:bismuth_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/black_bronze>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:black_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/black_steel>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:black_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/blue_steel>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:blue_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/bronze>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/cobalt>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:cobalt>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/copper>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/invar>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:invar>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/manyullyn>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:manyullyn>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/mithril>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:mithril>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/osmium>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:osmium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/red_steel>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:red_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/steel>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/titanium>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:titanium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/tungsten>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:tungsten>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/tungsten_steel>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:tungsten_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/wrought_iron>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:wrought_iron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/beryllium_copper>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:beryllium_copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/boron>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:boron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/nickel_silver>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:nickel_silver>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/javelin_head/zircaloy>, <tfc:ceramics/fired/mold/javelin_head>, <liquid:zircaloy>, 100, false, 40);

Casting.addTableRecipe(<tfc:metal/knife_blade/aluminium>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:aluminium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/bismuth_bronze>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:bismuth_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/black_bronze>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:black_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/black_steel>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:black_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/blue_steel>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:blue_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/bronze>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/cobalt>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:cobalt>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/copper>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/invar>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:invar>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/manyullyn>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:manyullyn>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/mithril>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:mithril>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/osmium>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:osmium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/red_steel>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:red_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/steel>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/titanium>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:titanium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/tungsten>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:tungsten>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/tungsten_steel>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:tungsten_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/wrought_iron>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:wrought_iron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/beryllium_copper>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:beryllium_copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/boron>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:boron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/nickel_silver>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:nickel_silver>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/knife_blade/zircaloy>, <tfc:ceramics/fired/mold/knife_blade>, <liquid:zircaloy>, 100, false, 40);

Casting.addTableRecipe(<tfc:metal/mace_head/aluminium>, <tfc:ceramics/fired/mold/mace_head>, <liquid:aluminium>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/bismuth_bronze>, <tfc:ceramics/fired/mold/mace_head>, <liquid:bismuth_bronze>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/black_bronze>, <tfc:ceramics/fired/mold/mace_head>, <liquid:black_bronze>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/black_steel>, <tfc:ceramics/fired/mold/mace_head>, <liquid:black_steel>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/blue_steel>, <tfc:ceramics/fired/mold/mace_head>, <liquid:blue_steel>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/bronze>, <tfc:ceramics/fired/mold/mace_head>, <liquid:bronze>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/cobalt>, <tfc:ceramics/fired/mold/mace_head>, <liquid:cobalt>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/copper>, <tfc:ceramics/fired/mold/mace_head>, <liquid:copper>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/invar>, <tfc:ceramics/fired/mold/mace_head>, <liquid:invar>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/manyullyn>, <tfc:ceramics/fired/mold/mace_head>, <liquid:manyullyn>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/mithril>, <tfc:ceramics/fired/mold/mace_head>, <liquid:mithril>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/osmium>, <tfc:ceramics/fired/mold/mace_head>, <liquid:osmium>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/red_steel>, <tfc:ceramics/fired/mold/mace_head>, <liquid:red_steel>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/steel>, <tfc:ceramics/fired/mold/mace_head>, <liquid:steel>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/titanium>, <tfc:ceramics/fired/mold/mace_head>, <liquid:titanium>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/tungsten>, <tfc:ceramics/fired/mold/mace_head>, <liquid:tungsten>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/tungsten_steel>, <tfc:ceramics/fired/mold/mace_head>, <liquid:tungsten_steel>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/wrought_iron>, <tfc:ceramics/fired/mold/mace_head>, <liquid:wrought_iron>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/beryllium_copper>, <tfc:ceramics/fired/mold/mace_head>, <liquid:beryllium_copper>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/boron>, <tfc:ceramics/fired/mold/mace_head>, <liquid:boron>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/nickel_silver>, <tfc:ceramics/fired/mold/mace_head>, <liquid:nickel_silver>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/mace_head/zircaloy>, <tfc:ceramics/fired/mold/mace_head>, <liquid:zircaloy>, 200, false, 80);

Casting.addTableRecipe(<tfc:metal/pick_head/aluminium>, <tfc:ceramics/fired/mold/pick_head>, <liquid:aluminium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/bismuth_bronze>, <tfc:ceramics/fired/mold/pick_head>, <liquid:bismuth_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/black_bronze>, <tfc:ceramics/fired/mold/pick_head>, <liquid:black_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/black_steel>, <tfc:ceramics/fired/mold/pick_head>, <liquid:black_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/blue_steel>, <tfc:ceramics/fired/mold/pick_head>, <liquid:blue_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/bronze>, <tfc:ceramics/fired/mold/pick_head>, <liquid:bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/cobalt>, <tfc:ceramics/fired/mold/pick_head>, <liquid:cobalt>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/copper>, <tfc:ceramics/fired/mold/pick_head>, <liquid:copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/invar>, <tfc:ceramics/fired/mold/pick_head>, <liquid:invar>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/manyullyn>, <tfc:ceramics/fired/mold/pick_head>, <liquid:manyullyn>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/mithril>, <tfc:ceramics/fired/mold/pick_head>, <liquid:mithril>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/osmium>, <tfc:ceramics/fired/mold/pick_head>, <liquid:osmium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/red_steel>, <tfc:ceramics/fired/mold/pick_head>, <liquid:red_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/steel>, <tfc:ceramics/fired/mold/pick_head>, <liquid:steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/titanium>, <tfc:ceramics/fired/mold/pick_head>, <liquid:titanium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/tungsten>, <tfc:ceramics/fired/mold/pick_head>, <liquid:tungsten>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/tungsten_steel>, <tfc:ceramics/fired/mold/pick_head>, <liquid:tungsten_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/wrought_iron>, <tfc:ceramics/fired/mold/pick_head>, <liquid:wrought_iron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/beryllium_copper>, <tfc:ceramics/fired/mold/pick_head>, <liquid:beryllium_copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/boron>, <tfc:ceramics/fired/mold/pick_head>, <liquid:boron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/nickel_silver>, <tfc:ceramics/fired/mold/pick_head>, <liquid:nickel_silver>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/pick_head/zircaloy>, <tfc:ceramics/fired/mold/pick_head>, <liquid:zircaloy>, 100, false, 40);

Casting.addTableRecipe(<tfc:metal/propick_head/aluminium>, <tfc:ceramics/fired/mold/propick_head>, <liquid:aluminium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/bismuth_bronze>, <tfc:ceramics/fired/mold/propick_head>, <liquid:bismuth_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/black_bronze>, <tfc:ceramics/fired/mold/propick_head>, <liquid:black_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/black_steel>, <tfc:ceramics/fired/mold/propick_head>, <liquid:black_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/blue_steel>, <tfc:ceramics/fired/mold/propick_head>, <liquid:blue_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/bronze>, <tfc:ceramics/fired/mold/propick_head>, <liquid:bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/cobalt>, <tfc:ceramics/fired/mold/propick_head>, <liquid:cobalt>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/copper>, <tfc:ceramics/fired/mold/propick_head>, <liquid:copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/invar>, <tfc:ceramics/fired/mold/propick_head>, <liquid:invar>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/manyullyn>, <tfc:ceramics/fired/mold/propick_head>, <liquid:manyullyn>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/mithril>, <tfc:ceramics/fired/mold/propick_head>, <liquid:mithril>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/osmium>, <tfc:ceramics/fired/mold/propick_head>, <liquid:osmium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/red_steel>, <tfc:ceramics/fired/mold/propick_head>, <liquid:red_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/steel>, <tfc:ceramics/fired/mold/propick_head>, <liquid:steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/titanium>, <tfc:ceramics/fired/mold/propick_head>, <liquid:titanium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/tungsten>, <tfc:ceramics/fired/mold/propick_head>, <liquid:tungsten>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/tungsten_steel>, <tfc:ceramics/fired/mold/propick_head>, <liquid:tungsten_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/wrought_iron>, <tfc:ceramics/fired/mold/propick_head>, <liquid:wrought_iron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/beryllium_copper>, <tfc:ceramics/fired/mold/propick_head>, <liquid:beryllium_copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/boron>, <tfc:ceramics/fired/mold/propick_head>, <liquid:boron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/nickel_silver>, <tfc:ceramics/fired/mold/propick_head>, <liquid:nickel_silver>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/propick_head/zircaloy>, <tfc:ceramics/fired/mold/propick_head>, <liquid:zircaloy>, 100, false, 40);

Casting.addTableRecipe(<tfc:metal/saw_blade/aluminium>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:aluminium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/bismuth_bronze>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:bismuth_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/black_bronze>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:black_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/black_steel>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:black_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/blue_steel>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:blue_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/bronze>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/cobalt>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:cobalt>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/copper>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/invar>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:invar>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/manyullyn>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:manyullyn>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/mithril>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:mithril>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/osmium>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:osmium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/red_steel>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:red_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/steel>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/titanium>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:titanium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/tungsten>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:tungsten>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/tungsten_steel>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:tungsten_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/wrought_iron>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:wrought_iron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/beryllium_copper>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:beryllium_copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/boron>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:boron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/nickel_silver>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:nickel_silver>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/saw_blade/zircaloy>, <tfc:ceramics/fired/mold/saw_blade>, <liquid:zircaloy>, 100, false, 40);

Casting.addTableRecipe(<tfc:metal/scythe_blade/aluminium>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:aluminium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/bismuth_bronze>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:bismuth_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/black_bronze>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:black_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/black_steel>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:black_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/blue_steel>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:blue_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/bronze>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/cobalt>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:cobalt>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/copper>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/invar>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:invar>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/manyullyn>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:manyullyn>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/mithril>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:mithril>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/osmium>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:osmium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/red_steel>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:red_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/steel>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/titanium>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:titanium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/tungsten>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:tungsten>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/tungsten_steel>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:tungsten_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/wrought_iron>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:wrought_iron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/beryllium_copper>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:beryllium_copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/boron>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:boron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/nickel_silver>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:nickel_silver>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/scythe_blade/zircaloy>, <tfc:ceramics/fired/mold/scythe_blade>, <liquid:zircaloy>, 100, false, 40);

Casting.addTableRecipe(<tfc:metal/shovel_head/aluminium>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:aluminium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/bismuth_bronze>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:bismuth_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/black_bronze>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:black_bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/black_steel>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:black_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/blue_steel>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:blue_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/bronze>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:bronze>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/cobalt>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:cobalt>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/copper>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/invar>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:invar>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/manyullyn>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:manyullyn>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/mithril>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:mithril>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/osmium>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:osmium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/red_steel>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:red_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/steel>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/titanium>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:titanium>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/tungsten>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:tungsten>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/tungsten_steel>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:tungsten_steel>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/wrought_iron>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:wrought_iron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/beryllium_copper>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:beryllium_copper>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/boron>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:boron>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/nickel_silver>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:nickel_silver>, 100, false, 40);
Casting.addTableRecipe(<tfc:metal/shovel_head/zircaloy>, <tfc:ceramics/fired/mold/shovel_head>, <liquid:zircaloy>, 100, false, 40);

Casting.addTableRecipe(<tfc:metal/sword_blade/aluminium>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:aluminium>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/bismuth_bronze>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:bismuth_bronze>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/black_bronze>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:black_bronze>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/black_steel>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:black_steel>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/blue_steel>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:blue_steel>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/bronze>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:bronze>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/cobalt>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:cobalt>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/copper>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:copper>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/invar>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:invar>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/manyullyn>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:manyullyn>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/mithril>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:mithril>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/osmium>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:osmium>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/red_steel>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:red_steel>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/steel>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:steel>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/titanium>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:titanium>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/tungsten>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:tungsten>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/tungsten_steel>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:tungsten_steel>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/wrought_iron>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:wrought_iron>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/beryllium_copper>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:beryllium_copper>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/boron>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:boron>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/nickel_silver>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:nickel_silver>, 200, false, 80);
Casting.addTableRecipe(<tfc:metal/sword_blade/zircaloy>, <tfc:ceramics/fired/mold/sword_blade>, <liquid:zircaloy>, 200, false, 80);

// ADD MELTING
Melting.addRecipe(<liquid:aluminium> * 25, <contenttweaker:bauxite25>);
Melting.addRecipe(<liquid:aluminium> * 5, <contenttweaker:bauxite5>);
Melting.addRecipe(<liquid:aluminium> * 50, <contenttweaker:bauxite50>);
Melting.addRecipe(<liquid:aluminium> * 800, <contenttweaker:blockaluminium>);
Melting.addRecipe(<liquid:aluminium> * 800, <contenttweaker:blocksheetmetalaluminium>);
Melting.addRecipe(<liquid:aluminium_brass> * 800, <contenttweaker:blockaluminium_brass>);
Melting.addRecipe(<liquid:aluminium_brass> * 800, <contenttweaker:blocksheetmetalaluminium_brass>);
Melting.addRecipe(<liquid:antimony> * 25, <contenttweaker:stibnite25>);
Melting.addRecipe(<liquid:antimony> * 5, <contenttweaker:stibnite5>);
Melting.addRecipe(<liquid:antimony> * 50, <contenttweaker:stibnite50>);
Melting.addRecipe(<liquid:antimony> * 800, <contenttweaker:blockantimony>);
Melting.addRecipe(<liquid:antimony> * 800, <contenttweaker:blocksheetmetalantimony>);
Melting.addRecipe(<liquid:ardite> * 25, <contenttweaker:native_ardite25>);
Melting.addRecipe(<liquid:ardite> * 5, <contenttweaker:native_ardite5>);
Melting.addRecipe(<liquid:ardite> * 50, <contenttweaker:native_ardite50>);
Melting.addRecipe(<liquid:ardite> * 800, <contenttweaker:blockardite>);
Melting.addRecipe(<liquid:ardite> * 800, <contenttweaker:blocksheetmetalardite>);
Melting.addRecipe(<liquid:beryllium> * 800, <contenttweaker:blockberyllium>);
Melting.addRecipe(<liquid:beryllium> * 800, <contenttweaker:blocksheetmetalberyllium>);
Melting.addRecipe(<liquid:beryllium_copper> * 800, <contenttweaker:blockberyllium_copper>);
Melting.addRecipe(<liquid:beryllium_copper> * 800, <contenttweaker:blocksheetmetalberyllium_copper>);
Melting.addRecipe(<liquid:bismuth> * 25, <contenttweaker:bismuthinite25>);
Melting.addRecipe(<liquid:bismuth> * 5, <contenttweaker:bismuthinite5>);
Melting.addRecipe(<liquid:bismuth> * 50, <contenttweaker:bismuthinite50>);
Melting.addRecipe(<liquid:bismuth> * 800, <contenttweaker:blockbismuth>, 270);
Melting.addRecipe(<liquid:bismuth> * 800, <contenttweaker:blocksheetmetalbismuth>, 270);
Melting.addRecipe(<liquid:bismuth_bronze> * 800, <contenttweaker:blockbismuth_bronze>);
Melting.addRecipe(<liquid:bismuth_bronze> * 800, <contenttweaker:blocksheetmetalbismuth_bronze>);
Melting.addRecipe(<liquid:black_bronze> * 800, <contenttweaker:blockblack_bronze>);
Melting.addRecipe(<liquid:black_bronze> * 800, <contenttweaker:blocksheetmetalblack_bronze>);
Melting.addRecipe(<liquid:black_steel> * 800, <contenttweaker:blockblack_steel>);
Melting.addRecipe(<liquid:black_steel> * 800, <contenttweaker:blocksheetmetalblack_steel>);
Melting.addRecipe(<liquid:blue_steel> * 800, <contenttweaker:blockblue_steel>);
Melting.addRecipe(<liquid:blue_steel> * 800, <contenttweaker:blocksheetmetalblue_steel>);
Melting.addRecipe(<liquid:boron> * 800, <contenttweaker:blockboron>);
Melting.addRecipe(<liquid:boron> * 800, <contenttweaker:blocksheetmetalboron>);
Melting.addRecipe(<liquid:brass> * 800, <contenttweaker:blockbrass>);
Melting.addRecipe(<liquid:brass> * 800, <contenttweaker:blocksheetmetalbrass>);
Melting.addRecipe(<liquid:bronze> * 800, <contenttweaker:blockbronze>);
Melting.addRecipe(<liquid:bronze> * 800, <contenttweaker:blocksheetmetalbronze>);
Melting.addRecipe(<liquid:cobalt> * 25, <contenttweaker:cobaltite25>);
Melting.addRecipe(<liquid:cobalt> * 5, <contenttweaker:cobaltite5>);
Melting.addRecipe(<liquid:cobalt> * 50, <contenttweaker:cobaltite50>);
Melting.addRecipe(<liquid:cobalt> * 800, <contenttweaker:blockcobalt>);
Melting.addRecipe(<liquid:cobalt> * 800, <contenttweaker:blocksheetmetalcobalt>);
Melting.addRecipe(<liquid:constantan> * 800, <contenttweaker:blockconstantan>);
Melting.addRecipe(<liquid:constantan> * 800, <contenttweaker:blocksheetmetalconstantan>);
Melting.addRecipe(<liquid:copper> * 25, <contenttweaker:malachite25>);
Melting.addRecipe(<liquid:copper> * 25, <contenttweaker:native_copper25>);
Melting.addRecipe(<liquid:copper> * 25, <contenttweaker:tetrahedrite25>);
Melting.addRecipe(<liquid:copper> * 5, <contenttweaker:malachite5>);
Melting.addRecipe(<liquid:copper> * 5, <contenttweaker:native_copper5>);
Melting.addRecipe(<liquid:copper> * 5, <contenttweaker:tetrahedrite5>);
Melting.addRecipe(<liquid:copper> * 50, <contenttweaker:malachite50>);
Melting.addRecipe(<liquid:copper> * 50, <contenttweaker:native_copper50>);
Melting.addRecipe(<liquid:copper> * 50, <contenttweaker:tetrahedrite50>);
Melting.addRecipe(<liquid:copper> * 800, <contenttweaker:blockcopper>);
Melting.addRecipe(<liquid:copper> * 800, <contenttweaker:blocksheetmetalcopper>);
Melting.addRecipe(<liquid:electrum> * 800, <contenttweaker:blockelectrum>);
Melting.addRecipe(<liquid:electrum> * 800, <contenttweaker:blocksheetmetalelectrum>);
Melting.addRecipe(<liquid:ferroboron> * 800, <contenttweaker:blockferroboron>);
Melting.addRecipe(<liquid:ferroboron> * 800, <contenttweaker:blocksheetmetalferroboron>);
Melting.addRecipe(<liquid:gold> * 25, <contenttweaker:native_gold25>);
Melting.addRecipe(<liquid:gold> * 5, <contenttweaker:native_gold5>);
Melting.addRecipe(<liquid:gold> * 50, <contenttweaker:native_gold50>);
Melting.addRecipe(<liquid:gold> * 800, <contenttweaker:blockgold>);
Melting.addRecipe(<liquid:gold> * 800, <contenttweaker:blocksheetmetalgold>);
Melting.addRecipe(<liquid:hsla_steel> * 800, <contenttweaker:blockhsla_steel>);
Melting.addRecipe(<liquid:hsla_steel> * 800, <contenttweaker:blocksheetmetalhsla_steel>);
Melting.addRecipe(<liquid:invar> * 800, <contenttweaker:blockinvar>);
Melting.addRecipe(<liquid:invar> * 800, <contenttweaker:blocksheetmetalinvar>);
Melting.addRecipe(<liquid:lead> * 25, <contenttweaker:galena25>);
Melting.addRecipe(<liquid:lead> * 5, <contenttweaker:galena5>);
Melting.addRecipe(<liquid:lead> * 50, <contenttweaker:galena50>);
Melting.addRecipe(<liquid:lead> * 800, <contenttweaker:blocklead>, 328);
Melting.addRecipe(<liquid:lead> * 800, <contenttweaker:blocksheetmetallead>, 328);
Melting.addRecipe(<liquid:lithium> * 800, <contenttweaker:blocklithium>);
Melting.addRecipe(<liquid:lithium> * 800, <contenttweaker:blocksheetmetallithium>);
Melting.addRecipe(<liquid:magnesium> * 800, <contenttweaker:blockmagnesium>);
Melting.addRecipe(<liquid:magnesium> * 800, <contenttweaker:blocksheetmetalmagnesium>);
Melting.addRecipe(<liquid:magnesium_diboride> * 800, <contenttweaker:blockmagnesium_diboride>);
Melting.addRecipe(<liquid:magnesium_diboride> * 800, <contenttweaker:blocksheetmetalmagnesium_diboride>);
Melting.addRecipe(<liquid:manganese> * 800, <contenttweaker:blockmanganese>);
Melting.addRecipe(<liquid:manganese> * 800, <contenttweaker:blocksheetmetalmanganese>);
Melting.addRecipe(<liquid:manyullyn> * 800, <contenttweaker:blockmanyullyn>);
Melting.addRecipe(<liquid:manyullyn> * 800, <contenttweaker:blocksheetmetalmanyullyn>);
Melting.addRecipe(<liquid:mithril> * 800, <contenttweaker:blockmithril>);
Melting.addRecipe(<liquid:mithril> * 800, <contenttweaker:blocksheetmetalmithril>);
Melting.addRecipe(<liquid:nickel> * 25, <contenttweaker:garnierite25>);
Melting.addRecipe(<liquid:nickel> * 5, <contenttweaker:garnierite5>);
Melting.addRecipe(<liquid:nickel> * 50, <contenttweaker:garnierite50>);
Melting.addRecipe(<liquid:nickel> * 800, <contenttweaker:blocknickel>);
Melting.addRecipe(<liquid:nickel> * 800, <contenttweaker:blocksheetmetalnickel>);
Melting.addRecipe(<liquid:nickel_silver> * 800, <contenttweaker:blocknickel_silver>);
Melting.addRecipe(<liquid:nickel_silver> * 800, <contenttweaker:blocksheetmetalnickel_silver>);
Melting.addRecipe(<liquid:osmium> * 25, <contenttweaker:native_osmium25>);
Melting.addRecipe(<liquid:osmium> * 5, <contenttweaker:native_osmium5>);
Melting.addRecipe(<liquid:osmium> * 50, <contenttweaker:native_osmium50>);
Melting.addRecipe(<liquid:osmium> * 800, <contenttweaker:blockosmium>);
Melting.addRecipe(<liquid:osmium> * 800, <contenttweaker:blocksheetmetalosmium>);
Melting.addRecipe(<liquid:platinum> * 25, <contenttweaker:native_platinum25>);
Melting.addRecipe(<liquid:platinum> * 5, <contenttweaker:native_platinum5>);
Melting.addRecipe(<liquid:platinum> * 50, <contenttweaker:native_platinum50>);
Melting.addRecipe(<liquid:platinum> * 800, <contenttweaker:blockplatinum>);
Melting.addRecipe(<liquid:platinum> * 800, <contenttweaker:blocksheetmetalplatinum>);
Melting.addRecipe(<liquid:red_alloy> * 800, <contenttweaker:blockred_alloy>);
Melting.addRecipe(<liquid:red_alloy> * 800, <contenttweaker:blocksheetmetalred_alloy>);
Melting.addRecipe(<liquid:red_steel> * 800, <contenttweaker:blockred_steel>);
Melting.addRecipe(<liquid:red_steel> * 800, <contenttweaker:blocksheetmetalred_steel>);
Melting.addRecipe(<liquid:rose_gold> * 800, <contenttweaker:blockrose_gold>);
Melting.addRecipe(<liquid:rose_gold> * 800, <contenttweaker:blocksheetmetalrose_gold>);
Melting.addRecipe(<liquid:silver> * 25, <contenttweaker:native_silver25>);
Melting.addRecipe(<liquid:silver> * 5, <contenttweaker:native_silver5>);
Melting.addRecipe(<liquid:silver> * 50, <contenttweaker:native_silver50>);
Melting.addRecipe(<liquid:silver> * 800, <contenttweaker:blocksheetmetalsilver>);
Melting.addRecipe(<liquid:silver> * 800, <contenttweaker:blocksilver>);
Melting.addRecipe(<liquid:steel> * 800, <contenttweaker:blocksheetmetalsteel>);
Melting.addRecipe(<liquid:steel> * 800, <contenttweaker:blocksteel>);
Melting.addRecipe(<liquid:sterling_silver> * 800, <contenttweaker:blocksheetmetalsterling_silver>);
Melting.addRecipe(<liquid:sterling_silver> * 800, <contenttweaker:blocksterling_silver>);
Melting.addRecipe(<liquid:stone> * 50, <tfc_tinker:grout_brick>);
Melting.addRecipe(<liquid:thorium> * 800, <contenttweaker:blocksheetmetalthorium>);
Melting.addRecipe(<liquid:thorium> * 800, <contenttweaker:blockthorium>);
Melting.addRecipe(<liquid:tin> * 25, <contenttweaker:cassiterite25>);
Melting.addRecipe(<liquid:tin> * 5, <contenttweaker:cassiterite5>);
Melting.addRecipe(<liquid:tin> * 50, <contenttweaker:cassiterite50>);
Melting.addRecipe(<liquid:tin> * 800, <contenttweaker:blocksheetmetaltin>, 230);
Melting.addRecipe(<liquid:tin> * 800, <contenttweaker:blocktin>, 230);
Melting.addRecipe(<liquid:titanium> * 800, <contenttweaker:blocksheetmetaltitanium>);
Melting.addRecipe(<liquid:titanium> * 800, <contenttweaker:blocktitanium>);
Melting.addRecipe(<liquid:tungsten> * 25, <contenttweaker:wolframite25>);
Melting.addRecipe(<liquid:tungsten> * 5, <contenttweaker:wolframite5>);
Melting.addRecipe(<liquid:tungsten> * 50, <contenttweaker:wolframite50>);
Melting.addRecipe(<liquid:tungsten> * 800, <contenttweaker:blocksheetmetaltungsten>);
Melting.addRecipe(<liquid:tungsten> * 800, <contenttweaker:blocktungsten>);
Melting.addRecipe(<liquid:tungsten_steel> * 800, <contenttweaker:blocksheetmetaltungsten_steel>);
Melting.addRecipe(<liquid:tungsten_steel> * 800, <contenttweaker:blocktungsten_steel>);
Melting.addRecipe(<liquid:uranium> * 800, <contenttweaker:blocksheetmetaluranium>);
Melting.addRecipe(<liquid:uranium> * 800, <contenttweaker:blockuranium>);
Melting.addRecipe(<liquid:wrought_iron> * 25, <contenttweaker:hematite25>);
Melting.addRecipe(<liquid:wrought_iron> * 25, <contenttweaker:limonite25>);
Melting.addRecipe(<liquid:wrought_iron> * 25, <contenttweaker:magnetite25>);
Melting.addRecipe(<liquid:wrought_iron> * 5, <contenttweaker:hematite5>);
Melting.addRecipe(<liquid:wrought_iron> * 5, <contenttweaker:limonite5>);
Melting.addRecipe(<liquid:wrought_iron> * 5, <contenttweaker:magnetite5>);
Melting.addRecipe(<liquid:wrought_iron> * 50, <contenttweaker:hematite50>);
Melting.addRecipe(<liquid:wrought_iron> * 50, <contenttweaker:limonite50>);
Melting.addRecipe(<liquid:wrought_iron> * 50, <contenttweaker:magnetite50>);
Melting.addRecipe(<liquid:wrought_iron> * 800, <contenttweaker:blocksheetmetalwrought_iron>);
Melting.addRecipe(<liquid:wrought_iron> * 800, <contenttweaker:blockwrought_iron>);
Melting.addRecipe(<liquid:zinc> * 25, <contenttweaker:sphalerite25>);
Melting.addRecipe(<liquid:zinc> * 5, <contenttweaker:sphalerite5>);
Melting.addRecipe(<liquid:zinc> * 50, <contenttweaker:sphalerite50>);
Melting.addRecipe(<liquid:zinc> * 800, <contenttweaker:blocksheetmetalzinc>, 420);
Melting.addRecipe(<liquid:zinc> * 800, <contenttweaker:blockzinc>, 420);
Melting.addRecipe(<liquid:zircaloy> * 800, <contenttweaker:blocksheetmetalzircaloy>);
Melting.addRecipe(<liquid:zircaloy> * 800, <contenttweaker:blockzircaloy>);
Melting.addRecipe(<liquid:zirconium> * 800, <contenttweaker:blocksheetmetalzirconium>);
Melting.addRecipe(<liquid:zirconium> * 800, <contenttweaker:blockzirconium>);

// ADD HEATING
ItemRegistry.registerItemHeat(<tconstruct:materials:10>, 0.31, 480, true);
ItemRegistry.registerItemHeat(<tconstruct:materials:11>, 0.31, 480, true);
ItemRegistry.registerItemHeat(<tconstruct:materials:9>, 0.31, 480, true);
ItemRegistry.registerItemHeat(<tconstruct:soil:1>, 0.85, 480, false);
ItemRegistry.registerItemHeat(<tconstruct:soil:2>, 0.85, 480, false);
ItemRegistry.registerItemHeat(<tconstruct:soil:5>, 0.85, 480, false);

Heating.addRecipe("slime_crystal_1", <tconstruct:soil:1>, <tconstruct:materials:9>, 190, 480);
Heating.addRecipe("slime_crystal_2", <tconstruct:soil:2>, <tconstruct:materials:10>, 190, 480);
Heating.addRecipe("slime_crystal_3", <tconstruct:soil:5>, <tconstruct:materials:11>, 190, 480);

// TOOLTIPS
<tconstruct:piggybackpack>.addTooltip("Don't you dare use it while wearing a Wearable Backpack!");